### ISSUE TITLE
FiveM Server wont start

### ISSUE THREAD

**Issue by jackdaniels552** [parkervcp/eggs#1209] opened 2021-06-28 10:03 UTC
Panel Version: 1.4.2
Daemon Version: Latest (not sure where to check this fresh install)
Service: Fivem
Modified: Not modified

Expected Behavior:
Start FiveM Server
Actual Behavior: 
This Happens 

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:d0c9bf7cd93a519d5156472deacdb112ad2c6b037b638cddc1b1c9b200eb30ea 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:base_debian 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
This environment is not supported for running the Cfx.re platform server. Please run the Cfx.re platform server on a machine you control.
Stop bypassing this check and enabling one-day-fly GSPs. If you do this again, we'll stop offering public Linux builds.
This environment is not supported for running the Cfx.re platform server. Please run the Cfx.re platform server on a machine you control.
/home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: fork: retry: Resource temporarily unavailable
Steps to Reproduce: (Step by step what to do to cause the issue)
Start FiveM Server

**Comment by Software-Noob** [comment] 2021-06-28 10:06
Duplicate of #1187, please use the startup variable to choose a specific version. The latest version fetching right now is not supported.

**Closed by Software-Noob** 2021-06-28 10:06 UTC
