### ISSUE TITLE
[Egg Request]: QuiltMC (Should be similar to FabricMC)

### ISSUE THREAD

**Issue by HughSparks** [parkervcp/eggs#2374] opened 2023-07-17 05:05 UTC
### Does this expand an already existing service

Yes

### Link to a game or software

https://quiltmc.org/en/

### Links for the download

https://github.com/QuiltMC/quilt-installer

### Links for the install docs

https://github.com/QuiltMC/quilt-loader/wiki

**Comment by yesBad** [comment] 2023-07-17 06:03
Already has been requested and a working egg is available in pr's.

**Comment by parkervcp** [comment] 2023-07-17 12:28
duplicate of #2348

**Closed by parkervcp** 2023-07-17 12:28 UTC
Labels: egg request
