### ISSUE TITLE
yagpdb

### ISSUE THREAD

**Issue by DomiiBunn** [parkervcp/eggs#484] opened 2020-04-08 18:17 UTC
Service: yagpdb

Does this expand an already existing service: No

Link to bot: https://docs.yagpdb.xyz/development/self-hosting-with-docker

More or less everything is in the docs
The bot runs in go. It would be nice to have most of the env brought out as ptero variables ^.^

**Comment by gOOvER** [comment] 2020-04-15 15:20
duplicate of #326

**Closed** 2020-04-18 15:56 UTC
