### ISSUE TITLE
Universal Discord Bot Egg which supports all languages

### ISSUE THREAD

**Issue by S4qib** [parkervcp/eggs#818] opened 2020-11-28 21:45 UTC
Service: Universal Discord Bot hosting egg

Does this expand an already existing service: Y

Link to game: discord.js.org, https://pypi.org/project/discord.py/, https://github.com/teamreflex/DiscordPHP

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.

Links for install steps/docs:

discord.js.org, https://pypi.org/project/discord.py/, https://github.com/teamreflex/DiscordPHP

**Comment by parkervcp** [comment] 2020-11-28 22:30
No.

Duplicate of #666 Which I also said no to.

**Closed by parkervcp** 2020-11-28 22:30 UTC
