### ISSUE TITLE
[Bug]: Arma 3 Steamcmd download failing

### ISSUE THREAD

**Issue by Arcanum417** [parkervcp/eggs#2302] opened 2023-06-15 17:52 UTC
### Panel Version

1.10.4

### Wings Version

1.11.5

### Service

steamcmd_servers/arma/arma3

### Modified

No, I did not modify the egg

### Expected Behavior

1. Add @2989115282 to additional mods
2. Restart
3. Have @2989115282 folder with the downloaded mod

### Actual Behavior

There is no new folder because the addon wasn't downloaded. This started happening today with an error.
Here are the console log, steamcmd.log and stderr.log
https://pteropaste.com/plwmy2xqcuh6

### Steps To Reproduce

1. Add @2989115282 to additional mods
2. Restart
3. Don't have @2989115282 folder with the downloaded mod

### Install logs

https://pteropaste.com/2ruvelmvaae3

**Comment by QuintenQVD0** [comment] 2023-06-15 18:09
\+ your panel is out of date. Even if that is not the issue no support for older version!

**Comment by Arcanum417** [comment] 2023-06-15 18:42
> @Arcanum417 have you tryed reinstalling?

Yes! Fresh after reinstall.



> + your panel is out of date. Even if that is not the issue no support for older version!

I couldn't update in place after this version with docker in docker I am running, so I didn't bother trying to look into it yet.
Well, I am pretty sure you can very quickly replicate, all of the servers started doing this.

**Comment by QuintenQVD0** [comment] 2023-06-15 19:22
This is more for @lilkingjr1

**Comment by lilkingjr1** [comment] 2023-06-15 20:09
```
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
```
Well that's new... It's causing SteamCMD to exit with a non-successful exit code (even though the general operation seems to be successful), which the Yolk is interpreting as an error and not processing the mod after download. I was able to replicate on the latest panel version (it's irrelevant, but nonetheless). It's probably due to Steam's recent major update.

I'll have to look into it, but I have very limited time right now unfortunately. The current work-around would be to disable mod automatic updates for the server in the admin panel and manually upload/install mods for the time being.

**Comment by QuintenQVD0** [comment] 2023-06-16 04:26
> ```
> Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
> ```
> 
> Well that's new... It's causing SteamCMD to exit with a non-successful exit code (even though the general operation seems to be successful), which the Yolk is interpreting as an error and not processing the mod after download. I was able to replicate on the latest panel version (it's irrelevant, but nonetheless). It's probably due to Steam's recent major update.
> 
> I'll have to look into it, but I have very limited time right now unfortunately. The current work-around would be to disable mod automatic updates for the server in the admin panel and manually upload/install mods for the time being.

It is definitly steamcmd related as ark has the same issue. On the SDL github  they just relatedt the latest 2.x version and the nex release will be v3.

**Comment by S0UK** [comment] 2023-06-16 21:20
> > ```
> > Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> > dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Well that's new... It's causing SteamCMD to exit with a non-successful exit code (even though the general operation seems to be successful), which the Yolk is interpreting as an error and not processing the mod after download. I was able to replicate on the latest panel version (it's irrelevant, but nonetheless). It's probably due to Steam's recent major update.
> > I'll have to look into it, but I have very limited time right now unfortunately. The current work-around would be to disable mod automatic updates for the server in the admin panel and manually upload/install mods for the time being.
> 
> It is definitly steamcmd related as ark has the same issue. On the SDL github they just relatedt the latest 2.x version and the nex release will be v3.

Im having the same issue, with same errors on a fresh install of Ubuntu with a fresh install of Steamcmd

**Comment by Ravi-Pogaku** [comment] 2023-06-17 03:37
> > ```
> > Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> > dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Well that's new... It's causing SteamCMD to exit with a non-successful exit code (even though the general operation seems to be successful), which the Yolk is interpreting as an error and not processing the mod after download. I was able to replicate on the latest panel version (it's irrelevant, but nonetheless). It's probably due to Steam's recent major update.
> > I'll have to look into it, but I have very limited time right now unfortunately. The current work-around would be to disable mod automatic updates for the server in the admin panel and manually upload/install mods for the time being.
> 
> It is definitly steamcmd related as ark has the same issue. On the SDL github they just relatedt the latest 2.x version and the nex release will be v3.

A similar thing is happening to me when I attempt to update valheim dedicated server. Hopefully this is helpful.

`Box86 with Dynarec v0.2.7 c1c36745 built on May 31 2022 02:00:50
Redirecting stderr to '/root/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1686881296
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: Cannot dlopen("steamservice.so"/0xed644cb8, 2)

dlmopen libSDL3.so.0 failed: Cannot dlopen("libSDL3.so.0"/0xed660e90, 2)

OK
"@sSteamCmdForcePlatformType" = "linux"

Connecting anonymously to Steam Public...src/tier1/fileio.cpp (5510) : m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
src/common/framefunction.cpp (149) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[CHTTPClient::BFrameFuncHandleCompletedWorkItems] still registered
`

**Comment by QuintenQVD0** [comment] 2023-06-17 06:07
Can you all please stop saying i also have this issue. We confirmed it is there. But SDL v3 is not yet released. It is compailokg about a 32 bit lib. I tryed with a 64 bit lib but thag does not work. For me on debian  11 i do have this warning but it still downloads and updates the game just fine.

**Comment by QuintenQVD0** [comment] 2023-06-17 06:09
> > > ```
> > > Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> > > dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Well that's new... It's causing SteamCMD to exit with a non-successful exit code (even though the general operation seems to be successful), which the Yolk is interpreting as an error and not processing the mod after download. I was able to replicate on the latest panel version (it's irrelevant, but nonetheless). It's probably due to Steam's recent major update.
> > > I'll have to look into it, but I have very limited time right now unfortunately. The current work-around would be to disable mod automatic updates for the server in the admin panel and manually upload/install mods for the time being.
> > 
> > 
> > It is definitly steamcmd related as ark has the same issue. On the SDL github they just relatedt the latest 2.x version and the nex release will be v3.
> 
> A similar thing is happening to me when I attempt to update valheim dedicated server. I could not find "steamservice.so" and "libSDL3.so.0" on my system but the error is different. Hopefully this is helpful.
> 
> ```
> Box86 with Dynarec v0.2.7 c1c36745 built on May 31 2022 02:00:50
> Redirecting stderr to '/root/Steam/logs/stderr.txt'
> [  0%] Checking for available updates...
> [----] Verifying installation...
> Steam Console Client (c) Valve Corporation - version 1686881296
> -- type 'quit' to exit --
> Loading Steam API...dlmopen steamservice.so failed: Cannot dlopen("steamservice.so"/0xed644cb8, 2)
> 
> dlmopen libSDL3.so.0 failed: Cannot dlopen("libSDL3.so.0"/0xed660e90, 2)
> 
> OK
> "@sSteamCmdForcePlatformType" = "linux"
> 
> Connecting anonymously to Steam Public...src/tier1/fileio.cpp (5510) : m_vecRegisteredWriters.Count() == 0
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/tier1/fileio.cpp (5572) : CFileWriterThread already exited
> src/common/framefunction.cpp (149) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[CHTTPClient::BFrameFuncHandleCompletedWorkItems] still registered
> ```

You are on arm64 so you are using one of mine egc what is not supported here.

**Comment by lilkingjr1** [comment] 2023-06-17 06:41
@QuintenQVD0 If you have time (I do not), can you post what code SteamCMD exits with when this error occurs? SteamCMD runs fine it seems, even with the error, so maybe we can just ignore it in the mean time.

**Comment by QuintenQVD0** [comment] 2023-06-17 06:49
> @QuintenQVD0 If you have time (I do not), can you post what code SteamCMD exits with when this error occurs? SteamCMD runs fine it seems, even with the error, so maybe we can just ignore it in the mean time.

Steamcmd does not exit for me it just spits out the error en continues. If i upload the 64 bit .so file to steamapps / linux32  it give WRONGCLASS64 so it tryed to load it but it is ofc a 64 so file. It does not care if i upload it to the linux64 folder

**Comment by lilkingjr1** [comment] 2023-06-17 09:42
> Steamcmd does not exit for me it just spits out the error en continues.

Right, but even if it continues and completes it will eventually finish and give an exit code (0 if it is a successful run). I need to know what the exit code is when this error occurs.

**Comment by ZsombiiHUN** [comment] 2023-06-17 18:48
+1
![Screenshot_162](https://github.com/parkervcp/eggs/assets/72627661/1dd60bbb-e966-47a5-9715-95b7e2c7ae86)

**Comment by QuintenQVD0** [comment] 2023-06-17 18:49
> +1 ![Screenshot_162](https://user-images.githubusercontent.com/72627661/246626755-1dd60bbb-e966-47a5-9715-95b7e2c7ae86.png)

we are working on it

**Comment by ZsombiiHUN** [comment] 2023-06-17 18:51
> > +1 ![Screenshot_162](https://user-images.githubusercontent.com/72627661/246626755-1dd60bbb-e966-47a5-9715-95b7e2c7ae86.png)
> 
> we are working on it

Do you know an ETA?

**Comment by QuintenQVD0** [comment] 2023-06-17 19:06
> 

No. There is no changelog and we don't expect support from valve so we have to use trial and error to see if we can get it fixt

**Comment by Stage4000** [comment] 2023-06-17 19:14
FAQ:
1) They know this is happening.
2) You're not special, they know you have the problem too so save everyone some time and don't post the same thing that's already been posted a dozen times.
3) They're working on a fix, posting irrelevant things and asking for ETAs isn't going to speed it up.
4) Be patient, this is an open source project. If you have something to contribute then there is this magical thing called pull requests if you don't know what that is then you DO NOT HAVE ANYTHING FURTHER TO CONTRIBUTE, your comments will only slow things further.
5) Just don't.

**Comment by lilkingjr1** [comment] 2023-06-17 20:58
> Do you know an ETA?

@ZsombiiHUN I predict I will have this resolved today, but no promises. It may require a Yolk/image update, which takes time to fix and process.

**Comment by lilkingjr1** [comment] 2023-06-17 21:43
Please visit the PR above, try the test image, and leave a comment on the PR if it works for you. Do not use the test image after the PR gets merged.

**Closed** 2023-06-17 21:49 UTC
Labels: bug, waiting for image

**Comment by VibeGAMESNL** [comment] 2023-06-18 13:42
We are getting the same issue when we try to install an arma server.
installer is using: ghcr.io/parkervcp/installers:debian

**Comment by QuintenQVD0** [comment] 2023-06-18 14:17
> We are getting the same issue when we try to install an arma server. installer is using: ghcr.io/parkervcp/installers:debian
> 
> ![image](https://user-images.githubusercontent.com/66668585/246669070-95f9d9f7-6cd7-4586-a9a5-97f1502a0ae0.png)

this is a warning and can be ignored!
