### ISSUE TITLE
[Bug]: Ark

### ISSUE THREAD

**Issue by OtakuSweett** [parkervcp/eggs#2025] opened 2022-12-28 16:39 UTC
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

Ark Survival envolved

### Modified

No, I did not modify the egg

### Expected Behavior

Well, I hoped it would work xD

### Actual Behavior

My server doesn't start, it just stays for hours in "waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused"

I already opened and assigned the ports
7777
7778
27015
27020

### Steps To Reproduce

I just start it and flag these messages for hours

dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused

### Install logs

https://pteropaste.com/viz5rq

**Comment by parkervcp** [comment] 2022-12-28 16:47
Does the server ever get to where it's "running" in the panel? How much ram is allocated to the server?

**Comment by giancrack782** [comment] 2022-12-28 16:58
nope, it never reaches "running" it has 8 GB but I have the possibility of increasing it to 14GB

**Comment by giancrack782** [comment] 2022-12-28 16:58
> Does the server ever get to where it's "running" in the panel? How much ram is allocated to the server?


nope, it never reaches "running" it has 8 GB but I have the possibility of increasing it to 14GB

**Comment by parkervcp** [comment] 2022-12-28 18:38
Kill the server and run the startup again. When it starts looping please grab the entire startup.

**Comment by giancrack782** [comment] 2022-12-28 19:50
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_source 
Digest: sha256:9127081aaf80e38544b183d96d06cf610d865e1b67606f1173ba5f7737d4f1c9 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
Not updating game server as auto update was set to 0. Starting Server
:/home/container$ rmv() { echo -e "stopping server"; rcon -t rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD} -c saveworld && rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD} -c DoExit; }; trap rmv 15; cd ShooterGame/Binaries/Linux && ./ShooterGameServer ${SERVER_MAP}?listen?SessionName="${SESSION_NAME}"?ServerPassword=${ARK_PASSWORD}?ServerAdminPassword=${ARK_ADMIN_PASSWORD}?Port=${SERVER_PORT}?RCONPort=${RCON_PORT}?QueryPort=${QUERY_PORT}?RCONEnabled=True$( [ "$BATTLE_EYE" == "1" ] || printf %s ' -NoBattlEye' ) -server ${ARGS} -log & until echo "waiting for rcon connection..."; rcon -t rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD}; do sleep 5; done
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
Shutdown handler: initalize.
Using binned.
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused

**Comment by QuintenQVD0** [comment] 2023-01-04 10:34
> Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_source

try setting the image to `ghcr.io/parkervcp/steamcmd:debian` It can take up to 10 minutes for it to start.
What is your kernel version?

**Comment by ovingiv** [comment] 2023-01-05 21:17
> try setting the image to `ghcr.io/parkervcp/steamcmd:debian` It can take up to 10 minutes for it to start.
> What is your kernel version?

I too am having this issue.
Adding the image still runs into the same issue
```container@pterodactyl~ Error Event [8207dfcc-4d0d-4cae-afe5-9a01a822e4e0]: environment/docker: failed to start container: Error response from daemon: driver failed programming external connectivity on endpoint a04ebe28-aff7-4ec5-b23a-3ca5b6baf89a (8fc453717075695ba672c9943c8f1a6a20b81f9ec081ab270cc49b9d8042ffa2): Error starting userland proxy: listen tcp4 <redacted>:27020: bind: cannot assign requested address```

**Comment by xTITUSMAXIMUSX** [comment] 2023-01-07 22:34
I was curious to see what the issue was. I spun up the default egg as is and I also was getting the same `waiting for rcon connection...` error message. But I saw the memory keep growing and thought that the game is still trying to launch and after about 2 minutes the server officially started and the error went away.

> waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27003: connect: connection refused
waiting for rcon connection...
read tcp 127.0.0.1:44382->127.0.0.1:27003: i/o timeout
waiting for rcon connection...
Waiting commands for 127.0.0.1:27003 (or type :q to exit)
container@pterodactyl~ Server marked as running...

**Comment by ovingiv** [comment] 2023-01-07 22:57
> I was curious to see what the issue was. I spun up the default egg as is and I also was getting the same `waiting for rcon connection...` error message. But I saw the memory keep growing and thought that the game is still trying to launch and after about 2 minutes the server officially started and the error went away.<

How much ram did you give it?
What ports did you add?

**Comment by peregrinatio** [comment] 2023-01-08 02:54
> I was curious to see what the issue was. I spun up the default egg as is and I also was getting the same `waiting for rcon connection...` error message. But I saw the memory keep growing and thought that the game is still trying to launch and after about 2 minutes the server officially started and the error went away.
> 
> ```
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> dial tcp 127.0.0.1:27003: connect: connection refused
> waiting for rcon connection...
> read tcp 127.0.0.1:44382->127.0.0.1:27003: i/o timeout
> waiting for rcon connection...
> Waiting commands for 127.0.0.1:27003 (or type :q to exit)
> container@pterodactyl~ Server marked as running...
> ```

Likewise here. I used standard ports, standard config. I just left it alone and after a short while the error stopped and it was up and running fine.

**Comment by ovingiv** [comment] 2023-01-08 15:31
So removing port 27020 from the egg allows it to start... Only gave it 7777, 7778 and 27015. It started up within 2 minutes.

**Comment by xTITUSMAXIMUSX** [comment] 2023-01-08 15:42
> > I was curious to see what the issue was. I spun up the default egg as is and I also was getting the same `waiting for rcon connection...` error message. But I saw the memory keep growing and thought that the game is still trying to launch and after about 2 minutes the server officially started and the error went away.<
> 
> How much ram did you give it? What ports did you add?

I gave the RAM unlimited but it looks like it capped out at 4.1GB

I gave it 3 ports. 1 for the server, 1 for the rcon and 1 got the game query. I made sure the exposed port numbers selected at the top of the form when selecting extra ports to match the server config at the bottom. Just choose which ports go where. I hope that makes sense lol!

**Comment by Software-Noob** [comment] 2023-01-08 22:31
Duplicate of #1738 #1732 #1181 #1091

Also documented in the [egg readme.](https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/ark_survival_evolved#rcon)

---

The egg checks every 5 seconds whether RCON is available or not. It will continue doing so until it can connect. ARK requires RCON for console output. You must wait for the server to start before it can connect to the RCON. This logic could be improved, but right now, that's how ARK works due to the lack of a proper console.

Ports do not affect the startup of the server and RCON unless you've manually modified the startup parameters and have duplicate ports. RCON port is optional as documented in the readme and only if you want to expose it. The container connects to it locally.

**To troubleshoot**, create a new server and **do not modify** any variables. Ensure that:

* Enough memory is allocated (+8-14GB depending on map)
* There are no errors for missing files due to a failed install or process crashing.

You might miss errors if you're not careful since the RCON check will keep spamming even after the process exits. Server startup depends on your resources, but it takes time.

---

When modifying a server, broken mods and invalid map names will cause the server to never start. Manually modifying startup parameters ports or anything related to RCON can cause it to fail.

**Comment by QuintenQVD0** [comment] 2023-05-19 16:00
The egg works fine so if you need more help then come to the discord

**Closed by QuintenQVD0** 2023-05-19 16:00 UTC
Labels: bug, not confirmed

**Comment by smolf** [comment] 2023-06-22 13:43
got the same problem 
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
waiting for rcon connection...
dial tcp 0.0.0.0:7777: connect: connection refused
waiting for rcon connection...
dial tcp 0.0.0.0:7777: connect: connection refused
waiting for rcon connection...
dial tcp 0.0.0.0:7777: connect: connection refused
waiting for rcon connection...
dial tcp 0.0.0.0:7777: connect: connection refused

**Comment by parkervcp** [comment] 2023-06-22 13:47
@smolf This is not an issue as it's waiting for your server to start. Any support for this is in discord.

**Comment by FelixKawaii** [comment] 2023-06-29 12:39
Same error,
Ports opened: 7777, 7778, 27021 (Query port, different because 27015 is already taken)

I gave it 30 gigs of RAM, let it do it's thing over night just to be safe.

It reaches running state in a few minutes but I am unable to connect to it or find it in the server browser.

https://pastebin.com/GC3nyELs
https://imgur.com/a/22hrHzX

**Comment by QuintenQVD0** [comment] 2023-06-29 13:48
> 

server is running. have you tryed using the steam query tool to see if it shows?
and is UDP and TCP forwarded. but same for you support is not here but in the discord.

**Comment by FelixKawaii** [comment] 2023-06-29 20:08
Steam query tool detects it but when connecting I have Server is not responding
Also sorry if I'm blind can you provide me with the link to the discord?

**Comment by QuintenQVD0** [comment] 2023-06-29 20:43
> Steam query tool detects it but when connecting I have Server is not responding Also sorry if I'm blind can you provide me with the link to the discord?

Pterodactyl.io top right or footer

**Comment by Kvaka** [comment] 2024-01-23 17:15
And what if I get this message: cli: auth: rcon: rcon: read packet size: read tcp 172.18.0.2:36770->94.253.138.202:20002: i/o timeout
![chrome_3S8pZv4RTN](https://github.com/parkervcp/eggs/assets/142451943/b3003edb-41b7-42b5-8017-c50e271a5628)

**Comment by QuintenQVD0** [comment] 2024-01-23 17:24
> And what if I get this message: cli: auth: rcon: rcon: read packet size: read tcp 172.18.0.2:36770->94.253.138.202:20002: i/o timeout ![chrome_3S8pZv4RTN](https://private-user-images.githubusercontent.com/142451943/299038362-b3003edb-41b7-42b5-8017-c50e271a5628.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzA5NDMsIm5iZiI6MTcwNjAzMDY0MywicGF0aCI6Ii8xNDI0NTE5NDMvMjk5MDM4MzYyLWIzMDAzZWRiLTQxYjctNDJiNS04MDE3LWM1MGUyNzFhNTYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNzI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODM3YzY5YmU0YWE3MDk3ZTRjOGNmNjZjNTRkYTQ2NWJlMWYwYTQ2N2NhNjBiZmFlNmJmNjNkMjFkOTMzNzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iXBaJ-ssLQPYPy9hFFM5KhwFSshWd2RX7WjZrV5kNpQ)

Don't use old issues, come to the discord for this!
