### ISSUE TITLE
FiveM

### ISSUE THREAD

**Issue by The-MG** [parkervcp/eggs#1193] opened 2021-06-21 20:31 UTC
Panel Version: 1.4.2
Daemon Version: 1.4.3
Service: FiveM
Modified: no

Expected Behavior:
Install FiveM and play it
Actual Behavior:
Install FiveM and get the following error: 
/home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: fork: retry: Resource temporarily unavailable

Steps to Reproduce: 
Install FiveM and try to start server.

**Comment by iamkubi** [comment] 2021-06-21 20:56
This is probably caused by the pid limits added in wings 1.4.4.  You can increase the limits in the Wings config file by defining the `container_pid_limit` setting.

**Comment by The-MG** [comment] 2021-06-22 06:17
> This is probably caused by the pid limits added in wings 1.4.4. You can increase the limits in the Wings config file by defining the `container_pid_limit` setting.

How exactly can I do that?

**Comment by Software-Noob** [comment] 2021-06-22 08:17
> > This is probably caused by the pid limits added in wings 1.4.4. You can increase the limits in the Wings config file by defining the `container_pid_limit` setting.
> 
> How exactly can I do that?

Did you

> This is probably caused by the pid limits added in wings 1.4.4. You can increase the limits in the Wings config file by defining the `container_pid_limit` setting.

This was only added in 1.4.4



> Panel Version: 1.4.2
> Daemon Version: 1.4.3
> Service: FiveM
> Modified: no
> 
> Expected Behavior:
> Install FiveM and play it
> Actual Behavior:
> Install FiveM and get the following error:
> /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: fork: retry: Resource temporarily unavailable
> 
> Steps to Reproduce:
> Install FiveM and try to start server.

It looks like you have set the version to `latest`, right now the latest version fetching is not supported and it's something that is being discussed with the fivem team.

**Comment by parkervcp** [comment] 2021-06-22 13:21
This is related to the issue with the fivem team blocking my install script and not the wings pid limit. I am closing this out as a duplicate of #1187

**Closed by parkervcp** 2021-06-22 13:21 UTC
