### ISSUE TITLE
[Bug]: we can no longer choose our version with egg of PocketMine

### ISSUE THREAD

**Issue by Sulfuritium** [parkervcp/eggs#1459] opened 2021-12-11 10:23 UTC
### Panel Version

1.6.6

### Wings Version

Linux (amd64)

### Service

pocketmine-MP

### Modified

No, I did not modify the egg

### Expected Behavior

To be able to choose the version of our pocketmine server

### Actual Behavior

There is no version box, only "Github Package" and "match"

### Steps To Reproduce

create a server
Choose PocketMine-MP

**Comment by QuintenQVD0** [comment] 2021-12-11 10:29
It got removed in a pull request by @gOOvER and aproved by @Software-Noob so there defintly will be a good reason for that. (#1371)

**Comment by gOOvER** [comment] 2021-12-11 10:34
Only Latest is supported. Dev of Pocketmine only support latest and for Windows Minecraft also only latest supported

**Comment by Sulfuritium** [comment] 2021-12-11 10:36
I'm sorry, but it's not a good decision: version 4.0 of Pocketmine has been released, but most servers remain in version 3.0 for the sake of incompatibility of plugins. In short, basically your "good reason" means that we can no longer create a server in version 3.0 since it is installing the latest version, so 4.0 ... This blocks everyone

**Comment by gOOvER** [comment] 2021-12-11 10:37
> I'm sorry, but it's not a good decision: version 4.0 of Pocketmine has been released, but most servers remain in version 3.0 for the sake of incompatibility of plugins. In short, basically your "good reason" means that we can no longer create a server in version 3.0 since it is installing the latest version, so 4.0 ... This blocks everyone

Only for illegall Versions of Minecraft for Windows and we don't support that.

**Comment by royaljacques** [comment] 2021-12-11 14:43
I do not agree for the children, I dev on pm3, and pm4. I do not agree that they do not wait the end of the pm3 to change.

**Comment by Software-Noob** [comment] 2021-12-11 14:49
This change was done because older versions are not supported, and PM4 was not released at the time. At this moment, both are supported, with PM3 lasting until March 1st, 2022. I'll add an option to choose the branch of 3 or 4.

**Comment by gOOvER** [comment] 2021-12-11 15:24
> This change was done because older versions are not supported, and PM4 was not released at the time. At this moment, both are supported, with PM3 lasting until March 1st, 2022. I'll add an option to choose the branch of 3 or 4.
> 
> The current version fetching is also broken, because it looks for the latest release on Github, and now they're all mixed.

i would stay on lastest and not add such an option. If he is a Dev, he can add this easily himself.

**Comment by Software-Noob** [comment] 2021-12-11 15:30
The developers support both pm3 and pm4, and the Github releases are mixed, containing both of them. Right now, the latest release is pm3 on Github, which would be installed. Tomorrow it might be pm4 again. It's not intended behavior.

Plugin compatibility is a big thing. There's no reason to downplay others' requirements.

**Comment by dktapps** [comment] 2021-12-11 15:50
PocketMine-MP developer here.

PocketMine-MP 4.0.0 was released on 1st December, 2021.

However, as recently announced to our users, the 3.x line of releases will continue to be supported with protocol updates until March 1st, 2021. The reason for this is because 4.0 is a major update with a large amount of changes, which most plugins have not yet been updated for. Migrations are starting to happen already, but it will take time. In the meantime, I expect many users will want to remain on 3.x until the plugins they want to use have been updated. More information: https://github.com/pmmp/PocketMine-MP/issues/4561

Removing the version selection is just harmful to users. While the dev team may not provide technical support for older versions, it does **not** mean that Pterodactyl should remove their choice to use them. For example, many users prefer to stay on older versions of PocketMine-MP so that they can play older versions of Minecraft. Lack of bugfix support is just a risk they choose to take.

> The current version fetching is also broken, because it looks for the latest release on Github, and now they're all mixed.

For this you should either use https://get.pmmp.io (as described in the [official documentation](https://doc.pmmp.io/en/rtfd/installation/get-dot-pmmp-dot-io.html)).

For PM4:
```
curl -sL https://get.pmmp.io | bash -s -
```

For PM3:
```
curl -sL https://get.pmmp.io | bash -s - -v pm3
```

Alternatively, if you don't trust get.pmmp.io, you can interact with the following APIs to get build infos:

https://update.pmmp.io/api?channel=stable
https://update.pmmp.io/api?channel=pm3

**Comment by gOOvER** [comment] 2021-12-11 16:38
@dktapps I dont see any option to use older Versions of MC for Windows or MC for Mobiles. So it's hard to maintain older Version, since main php is 8. In the egg we must set for every Version the used php Version. So This change was; only LATEST will be supported, since PM Team gives no support for older Versions.


Ok, as i see, you suipport 3.x and 4.x. The question is how long you give support for the 3.x ?

**Comment by gOOvER** [comment] 2021-12-11 17:44
Ok, found it; 

```
The 3.x line of releases is now OBSOLETE. It will be discontinued after March 1st, 2022.
Please prepare to upgrade to 4.0 or newer before that date.
```

So better, the eg shpuld oly support 4.0 as is marked as latest

**Comment by dktapps** [comment] 2021-12-11 17:52
You can simply not update, or use a launcher such as https://github.com/MCMrARM/mc-w10-version-launcher. Neither of these options involve pirating the game.

**Comment by gOOvER** [comment] 2021-12-11 17:55
> You can simply not update, or use a launcher such as [MCMrARM/mc-w10-version-launcher](https://github.com/MCMrARM/mc-w10-version-launcher). Neither of these options involve pirating the game.

No need to use that.

**Comment by dktapps** [comment] 2021-12-11 17:58
> Edit: 4.0 is not marked as latest. Still 3.x is latest @dktapps

That's just GitHub Releases. I can't control which one appears at the top, since they are ordered by date of release.

The better way is to use these:
 
> either use https://get.pmmp.io (as described in the [official documentation](https://doc.pmmp.io/en/rtfd/installation/get-dot-pmmp-dot-io.html)), or update.pmmp.io (see below).
> 
> For PM4:
> 
> ```
> curl -sL https://get.pmmp.io | bash -s -
> ```
> 
> For PM3:
> 
> ```
> curl -sL https://get.pmmp.io | bash -s - -v pm3
> ```
> 
> Alternatively, if you don't trust get.pmmp.io, you can interact with the following APIs to get build infos:
> 
> https://update.pmmp.io/api?channel=stable
> https://update.pmmp.io/api?channel=pm3

**Comment by dktapps** [comment] 2021-12-11 17:59
> > You can simply not update, or use a launcher such as [MCMrARM/mc-w10-version-launcher](https://github.com/MCMrARM/mc-w10-version-launcher). Neither of these options involve pirating the game.
> 
> No need to use that. Some users play with illegal Windows / Mobile Versions.

It's not your place to police those who may do that. The point is that there are legitimate ways to play older versions. Don't be so narrow-minded.

**Comment by gOOvER** [comment] 2021-12-11 18:00
> > > You can simply not update, or use a launcher such as [MCMrARM/mc-w10-version-launcher](https://github.com/MCMrARM/mc-w10-version-launcher). Neither of these options involve pirating the game.
> > 
> > 
> > No need to use that. Some users play with illegal Windows / Mobile Versions.
> 
> It's not your place to police those who may do that. The point is that there are legitimate ways to play older versions. Don't be so narrow-minded.

You cant download older versions of MC Windowes or MC Mobile ;) There is no option in Xbox or on Android. Only the latest

**Comment by dktapps** [comment] 2021-12-11 18:01
> > > > You can simply not update, or use a launcher such as [MCMrARM/mc-w10-version-launcher](https://github.com/MCMrARM/mc-w10-version-launcher). Neither of these options involve pirating the game.
> > > 
> > > 
> > > No need to use that. Some users play with illegal Windows / Mobile Versions.
> > 
> > 
> > It's not your place to police those who may do that. The point is that there are legitimate ways to play older versions. Don't be so narrow-minded.
> 
> You cant download older versions of MC Windowes or MC Mobile ;) There is no option in Xbox or on Android. Only the latest

I literally just told you 2 ways you can do exactly that...



> You can simply not update, or use a launcher such as https://github.com/MCMrARM/mc-w10-version-launcher. Neither of these options involve pirating the game.

**Comment by gOOvER** [comment] 2021-12-11 18:02
> > > > > You can simply not update, or use a launcher such as [MCMrARM/mc-w10-version-launcher](https://github.com/MCMrARM/mc-w10-version-launcher). Neither of these options involve pirating the game.
> > > > 
> > > > 
> > > > No need to use that. Some users play with illegal Windows / Mobile Versions.
> > > 
> > > 
> > > It's not your place to police those who may do that. The point is that there are legitimate ways to play older versions. Don't be so narrow-minded.
> > 
> > 
> > You cant download older versions of MC Windowes or MC Mobile ;) There is no option in Xbox or on Android. Only the latest
> 
> I literally just told you 2 ways you can do exactly that...
> 
> > You can simply not update, or use a launcher such as [MCMrARM/mc-w10-version-launcher](https://github.com/MCMrARM/mc-w10-version-launcher). Neither of these options involve pirating the game.

I know; only anwser your last comment. `The point is that there are legitimate ways to play older versions. Don't be so narrow-minded.`

I found not one Way to dl older versions

**Comment by Endermanbugzjfc** [comment] 2021-12-11 18:08
lol MCMrARM/mc-w10-version-launcher doesn't even work without an MS Store account that had purchased Minecraft.

**Comment by Software-Noob** [comment] 2021-12-11 18:10
Dylan provided legitimate methods to get older versions that require a Microsoft account, and being the developer of the project would probably know better what is supported. Would you please stop trying to start an argument for no reason.

There's a legitimate reason to offer other versions besides pm4. I will push a new update when I get home.

**Comment by Endermanbugzjfc** [comment] 2021-12-11 18:13
@gOOvER 

You are being too arrogant. You decided to remove the version because you think that you are the maintainer of the egg so you have the permission to remove the version selector. You only consider in one aspect that if you remove the version selector, the amount of illegal Minecraft players will decrease, and people will be happy with you, the people will worship you since you are like the king who can manage the egg and people loved what you did.

Some people still use an old version of Minecraft for many reasons, mostly to restore the old feeling of PVP. If you consider in more aspects, you should have thought about this.

**Comment by Endermanbugzjfc** [comment] 2021-12-11 18:14
> Dylan provided legitimate methods to get older versions that require a Microsoft account, and being the developer of the project would probably know better what is supported. Would you please stop trying to start an argument for no reason.
> 
> There's a legitimate reason to offer other versions besides pm4. I will push a new update when I get home.

I'm agreeing with dylan's statements.
"lol MCMrARM/mc-w10-version-launcher doesn't even work without an MS Store account that had purchased Minecraft." means players can't use the launcher to play Minecraft illegally.

**Comment by gOOvER** [comment] 2021-12-11 18:16
> Dylan provided legitimate methods to get older versions that require a Microsoft account, and being the developer of the project would probably know better what is supported. Would you please stop trying to start an argument for no reason.
> 
> There's a legitimate reason to offer other versions besides pm4. I will push a new update when I get home.

Have fun, to add all Version with all PHP Versions. That was the point and that was what Parker said; No need to support all Versions, because of different PHP Versions.

@Endermanbugzjfc No Need to support older Version; thats my opinion. 99% use older Versions because the kids don't want to pay for it

**Comment by Endermanbugzjfc** [comment] 2021-12-11 18:16
> > Dylan provided legitimate methods to get older versions that require a Microsoft account, and being the developer of the project would probably know better what is supported. Would you please stop trying to start an argument for no reason.
> > There's a legitimate reason to offer other versions besides pm4. I will push a new update when I get home.
> 
> Have fun, to add all Version with all PHP Versions. That was the point and that was what Parker said; No need to support all Versions, because of different PHP Versions.
> 
> @Endermanbugzjfc No Need to support older Version; thats my opinion. 99% use older Versions because the kids don't want to pay for it

https://github.com/parkervcp/eggs/issues/1459#issuecomment-991736289

**Comment by gOOvER** [comment] 2021-12-11 18:17
> > > Dylan provided legitimate methods to get older versions that require a Microsoft account, and being the developer of the project would probably know better what is supported. Would you please stop trying to start an argument for no reason.
> > > There's a legitimate reason to offer other versions besides pm4. I will push a new update when I get home.
> > 
> > 
> > Have fun, to add all Version with all PHP Versions. That was the point and that was what Parker said; No need to support all Versions, because of different PHP Versions.
> > @Endermanbugzjfc No Need to support older Version; thats my opinion. 99% use older Versions because the kids don't want to pay for it
> 
> Yes, it is YOUR opinion.

No need to read your useless Opinions ;)  Update the Egg yourself

**Comment by Software-Noob** [comment] 2021-12-11 19:02
Users can choose the latest pm3 or pm4 in the new egg version. Supporting older versions is something to discuss in the future due to PHP issues. Dylan mentioned on Discord creating an endpoint to fetch the required PHP binary.

**Closed** 2021-12-11 20:09 UTC
Labels: Bug
