### ISSUE TITLE
Game request: Red Dead Redemption 2

### ISSUE THREAD

**Issue by GamerXCZ** [parkervcp/eggs#423] opened 2020-02-01 12:28 UTC
RedM, for Red Dead Redemption 2 on PC. Launching now, based on the CitizenFX framework and Cfx.re technology.

Also see FiveM for GTA V. More documentation following later this month. Discuss it on the Cfx.re forums under the RedM categories. Yes, the 'now' above is a download button.

https://redm.gg/

**Comment by parkervcp** [comment] 2020-02-01 12:43
Literally a duplicate of #379

**Closed by parkervcp** 2020-02-01 12:43 UTC
