### ISSUE TITLE
Add Azuracast 

### ISSUE THREAD

**Issue by SuperKali** [parkervcp/eggs#1189] opened 2021-06-17 21:41 UTC
Service: Azuracast

Does this expand an already existing service: n

Link to game: https://azuracast.com

Links for server downloads: it's a docker.

Links for install steps/docs: https://docs.azuracast.com/en/getting-started/installation

**Comment by parkervcp** [comment] 2021-06-17 21:44
No

Duplicate of #953

**Closed by parkervcp** 2021-06-17 21:44 UTC
