### ISSUE TITLE
Nitrox Server

### ISSUE THREAD

**Issue by NhProGamer** [parkervcp/eggs#840] opened 2020-12-05 20:03 UTC
Nitrox mod is a mod for the game Subnautica for play on multiplayer
---------------

Service: Nitrox Mod for Subnautica

Does this expand an already existing service: Yes

Link to game: [](https://nitrox.rux.gg)

Links for server downloads:[]( https://nitrox.rux.gg/download)

Links for install steps/docs:

**The server is not officially available on linux but if you run with "wine" it works.**
we need to have bought subnautica because "Nitrox" uses the files of the game
install wine on the container
install winetricks for install dotnet 4.5 on wine
(winetricks is a script, look here: [SCRIPT](https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks) and here [THE GITHUB](https://github.com/Winetricks/winetricks)
we have to create a file named path.txt located where the server executable is, it defines where the game files are located.
"NitroxServer-Subnautica.exe.config" defines the settings of the server
(the port, admin password, server password etc...)

**Comment by gOOvER** [comment] 2020-12-05 20:05
duplicate of #465

**Closed** 2020-12-05 21:28 UTC
