### ISSUE TITLE
curseforge-generic egg has invalid not check in install script.

### ISSUE THREAD

**Issue by AlienXAXS** [parkervcp/eggs#942] opened 2021-01-24 23:06 UTC
https://github.com/parkervcp/eggs/blob/99e66c5b3d7ad90f981218e039870e76cc90f495/minecraft/java/forge/curseforge-generic/egg-curseforge-generic.json#L25

I am rather sure that the section that says: if [ ! -z ${FILES_JSON_ELEMENT} ] should not have the "not" operator there in the if statement.

I believe that this makes the if statement invalid, where as if the correct version was found in the json string, it'll assume it wasnt found and always install latest.

**Comment by acl1704** [comment] 2021-01-24 23:54
Is this a problem you've encountered? In any event I don't think anyone is supporting curseforge anymore. Could always make a PR. Also you need to use the issue template.

**Comment by parkervcp** [comment] 2021-01-25 00:21
duplicate of #934

**Closed by parkervcp** 2021-01-25 00:21 UTC
