### ISSUE TITLE
[Egg Request]: <Software/Game>

### ISSUE THREAD

**Issue by DevJernejTDO** [parkervcp/eggs#2014] opened 2022-12-21 22:54 UTC
### Does this expand an already existing service

Yes

### Link to a game or software

https://astroneer.space/

### Links for the download

https://store.steampowered.com/app/361420/ASTRONEER/

### Links for the install docs

https://astroneer.space/dedicatedserver/

**Comment by parkervcp** [comment] 2022-12-21 23:16
Duplicate of #544

**Closed by parkervcp** 2022-12-21 23:16 UTC
Labels: egg request
