### ISSUE TITLE
[Bug]:  FiveM dont work egg news Alpine

### ISSUE THREAD

**Issue by Mateusz57698** [parkervcp/eggs#1280] opened 2021-08-01 20:41 UTC
### Panel Version

1.4.1

### Wings Version

1.4.5

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server , configuration or play

### Actual Behavior

after manual installation of the selected artifact version and lastet, the server shows this message and does not start

"This environment is not supported for running the Cfx.re platform server. Please run the Cfx.re pl atform server on a machine you control directly (i.e. not using a GSP panel). Terminated containerepterodactyl- Server marked as offline...'

### Steps To Reproduce

Set version latest or install 
Or and manually entering the latest versions does the same

### Relevant log output

```shell
container@pterodactyl- Server marked as offline... [Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds... [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds.. container@pterodactyl- Server marked as starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/pterodactyl-images Digest: sha256:doc9bf7cd93a519d5156472deacdb112ad2c6b037b638cddc1bic9b200eb30ea Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:base_debian [Pterodactyl Daemon]: Finished pulling Docker container image :/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$ (pwd) /alpine/u sr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" t citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licensekey ${FIVEM_LICENSE} +set steam _webApikey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set tx AdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" This environment is not supported for running the Cfx.re platform server. Please run the Cfx.re pl atform server on a machine you control directly (i.e. not using a GSP panel). Terminated containerepterodactyl- Server marked as offline... $(pwd)/alpine/opt/cfx-server /FXServer +se -- "1" 1 || printf %s '+exec server.cfg' ) Detected server process in a crashed statel [Pterodactyl Daemon]: [Pterodactyl Daemon]: Exit code: 143 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

**Comment by parkervcp** [comment] 2021-08-01 20:52
duplicate of #1187

**Closed** 2021-08-01 20:52 UTC
Labels: Bug
