### ISSUE TITLE
[Bug]: Project Zomboid Egg Startup Crash (Build 41.66)

### ISSUE THREAD

**Issue by Cooleem** [parkervcp/eggs#1571] opened 2022-02-25 17:44 UTC
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

Project Zomboid

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it, play.

### Actual Behavior

Crashes with a Java error upon starting the server. This is not an issue with installing the server, but rather when the server attempts to make a backup upon the initial startup.

`LOG  : General     , 1645810595476> 591,444,405> Start making backup to: /home/container/.cache/backups/startup
ERROR: General     , 1645810595973> 591,444,903> java.util.concurrent.ExecutionException: java.io.IOException: No space left on device
ERROR: General     , 1645810595974> 591,444,903>        at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
ERROR: General     , 1645810595974> 591,444,903>        at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
ERROR: General     , 1645810595974> 591,444,903>        at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator.writeTo(ParallelScatterZipCreator.java:245)
ERROR: General     , 1645810595974> 591,444,904>        at zombie.core.backup.ZipBackup.makeBackupFile(ZipBackup.java:147)
ERROR: General     , 1645810595974> 591,444,904>        at zombie.core.backup.ZipBackup.onStartup(ZipBackup.java:47)
ERROR: General     , 1645810595974> 591,444,904>        at zombie.network.GameServer.main(GameServer.java:623)
ERROR: General     , 1645810595974> 591,444,904> Caused by: java.io.IOException: No space left on device
ERROR: General     , 1645810595974> 591,444,904>        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
ERROR: General     , 1645810595974> 591,444,904>        at java.base/sun.nio.ch.FileDispatcherImpl.write(Unknown Source)
ERROR: General     , 1645810595974> 591,444,904>        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
ERROR: General     , 1645810595974> 591,444,904>        at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
ERROR: General     , 1645810595974> 591,444,904>        at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
ERROR: General     , 1645810595974> 591,444,904>        at java.base/sun.nio.ch.FileChannelImpl.write(Unknown Source)
ERROR: General     , 1645810595974> 591,444,904>        at java.base/java.nio.channels.Channels.writeFullyImpl(Unknown Source)
ERROR: General     , 1645810595975> 591,444,904>        at java.base/java.nio.channels.Channels.writeFully(Unknown Source)
ERROR: General     , 1645810595975> 591,444,904>        at java.base/java.nio.channels.Channels$1.write(Unknown Source)
ERROR: General     , 1645810595975> 591,444,904>        at org.apache.commons.compress.parallel.FileBasedScatterGatherBackingStore.writeOut(FileBasedScatterGatherBackingStore.java:65)
ERROR: General     , 1645810595975> 591,444,904>        at org.apache.commons.compress.archivers.zip.StreamCompressor$ScatterGatherBackingStoreCompressor.writeOut(StreamCompressor.java:291)
ERROR: General     , 1645810595975> 591,444,904>        at org.apache.commons.compress.archivers.zip.StreamCompressor.writeCounted(StreamCompressor.java:273)
ERROR: General     , 1645810595975> 591,444,904>        at org.apache.commons.compress.archivers.zip.StreamCompressor.write(StreamCompressor.java:207)
ERROR: General     , 1645810595975> 591,444,905>        at org.apache.commons.compress.archivers.zip.StreamCompressor.deflate(StreamCompressor.java:184)
ERROR: General     , 1645810595975> 591,444,905>        at org.apache.commons.compress.archivers.zip.ScatterZipOutputStream.addArchiveEntry(ScatterZipOutputStream.java:96)
ERROR: General     , 1645810595975> 591,444,905>        at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator$2.call(ParallelScatterZipCreator.java:191)
ERROR: General     , 1645810595975> 591,444,905>        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
ERROR: General     , 1645810595975> 591,444,905>        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ERROR: General     , 1645810595975> 591,444,905>        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ERROR: General     , 1645810595975> 591,444,905>        at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1645810595977> 591,444,907> Backup made in 500 ms
LOG  : General     , 1645810595978> 591,444,908> user database "/home/container/.cache/db/"Project.db"
ERROR: General     , 1645810596001> 591,444,931> No space left on device
Exception in thread "main" ERROR: General     , 1645810596002> 591,444,931> java.lang.UnsatisfiedLinkError: 'void org.sqlite.core.NativeDB._open_utf8(byte[], int)'
ERROR: General     , 1645810596002> 591,444,931>        at org.sqlite.core.NativeDB._open_utf8(Native Method)
ERROR: General     , 1645810596002> 591,444,931>        at org.sqlite.core.NativeDB._open(NativeDB.java:78)
ERROR: General     , 1645810596002> 591,444,932>        at org.sqlite.core.DB.open(DB.java:195)
ERROR: General     , 1645810596002> 591,444,932>        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
ERROR: General     , 1645810596002> 591,444,932>        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
ERROR: General     , 1645810596002> 591,444,932>        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
ERROR: General     , 1645810596002> 591,444,932>        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
ERROR: General     , 1645810596002> 591,444,932>        at org.sqlite.JDBC.createConnection(JDBC.java:115)
ERROR: General     , 1645810596002> 591,444,932>        at org.sqlite.JDBC.connect(JDBC.java:90)
ERROR: General     , 1645810596002> 591,444,932>        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
ERROR: General     , 1645810596002> 591,444,932>        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
ERROR: General     , 1645810596002> 591,444,932>        at zombie.util.PZSQLUtils.getConnection(PZSQLUtils.java:76)
ERROR: General     , 1645810596002> 591,444,932>        at zombie.network.ServerWorldDatabase.create(ServerWorldDatabase.java:333)
ERROR: General     , 1645810596002> 591,444,932>        at zombie.network.GameServer.main(GameServer.java:628)
src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.`

The way to temporarily resolve this issue is by setting **BackupsOnStart=false** within the server configuration file. By default, this is found in **/.cache/Server/"Project.ini**. This issue is only reproducible on the Project Zomboid game build 41.66, as this issue was not present within build 41.65. The Indie Stone has sent out a Twitter response to potentially fix this issue: [https://twitter.com/theindiestone/status/1497206924659630083](url). This may be a dependency issue, but I have not thoroughly investigated any further than this.

### Steps To Reproduce

Step 1. Import the egg into Pterodactyl.

Step 2. Create a server with the egg.

Step 3. Let the server install.

Step 4. Start the server.

Step 5. With the default server configuration, the error will produce by itself.

### Install logs

Not an install issue; it is a startup issue.

**Comment by Bazimek** [comment] 2022-02-25 17:46
![image](https://user-images.githubusercontent.com/17622398/155762565-621db555-ad6f-412c-9c1d-03fd526283c7.png)
Same for me.

**Comment by Software-Noob** [comment] 2022-02-25 18:09
I can't reproduce. Backup is successfully created, and the server starts. You might be indeed out of disk space/memory, depending on how the backup is performed. For example, Pterodactyl only has 100MB of tmpfs by default. Type `df -h` and double-check.

```
LOG  : General     , 1645812342717> 8,268,354> Start making backup to: /home/container/.cache/backups/startup
LOG  : General     , 1645812342768> 8,268,404> compressionElapsed=24ms, mergingElapsed=21ms
LOG  : General     , 1645812342770> 8,268,406> Backup made in 52 ms
LOG  : General     , 1645812342771> 8,268,407> Start making backup to: /home/container/.cache/backups/version
LOG  : General     , 1645812342774> 8,268,410> compressionElapsed=2ms, mergingElapsed=1ms
LOG  : General     , 1645812342775> 8,268,411> Backup made in 4 ms
LOG  : General     , 1645812342775> 8,268,412> user database "/home/container/.cache/db/"Project.db"
LOG  : General     , 1645812343314> 8,268,950> Administrator account 'admin' created.
LOG  : General     , 1645812343541> 8,269,178> admin password changed via -adminpassword option
LOG  : General     , 1645812343542> 8,269,178> Router detection/configuration starting.
LOG  : General     , 1645812343542> 8,269,178> If the server hangs here, set UPnP=false.
LOG  : Network     , 1645812355556> 8,281,192> No UPnP-enabled Internet gateway found, you must configure port forwarding on your gateway manually in order to make your server accessible from the Internet.
LOG  : Network     , 1645812355557> 8,281,193> Initialising Server Systems...
LOG  : Lua         , 1645812356052> 8,281,688> Loading: media/lua/shared/Sandbo
```

**Comment by Bazimek** [comment] 2022-02-25 18:54
I set the tmpfs to 250 and it is still not working with backups turned on. What about the tweet from the devs? IS possible that in our pterodactyl instances we are missing that dependency?

**Comment by Software-Noob** [comment] 2022-02-25 19:05
> I set the tmpfs to 250 and it is still not working with backups turned on. What about the tweet from the devs? IS possible that in our pterodactyl instances we are missing that dependency? Memory and disk size is fine. 

Docker ensures the dependencies and container environments are the same for everyone, and it works for me. My test server is a fresh one.

It's possible that existing servers have way larger save files. What is the output of your partition sizes? Also, any changes to Wings config requires restarting Wings and the container.

**Comment by Bazimek** [comment] 2022-02-25 19:16
![image](https://user-images.githubusercontent.com/17622398/155774527-b7085af7-16a0-4831-bd55-243bbbdb1687.png)

**Comment by peakzero** [comment] 2022-03-01 00:54
Also experiencing this issue on an older save, confirmed does not happen with a fresh save on the same server.

**Comment by r3in3r** [comment] 2022-12-14 14:03
Can the _backupsonstart_ be set on false automatically or set as a variable so that I can set default to false so that it stop affecting servers

**Comment by JadenH** [comment] 2023-08-07 07:03
I was able to resolve this by increasing the tmpfs size: https://pterodactyl.io/wings/1.0/configuration.html#other-values

**Comment by QuintenQVD0** [comment] 2023-08-07 10:12
Closed as this was indeed a tempfs issue.

**Closed by QuintenQVD0** 2023-08-07 10:12 UTC
Labels: not confirmed
