### ISSUE TITLE
CFX Crash

### ISSUE THREAD

**Issue by discovery855** [parkervcp/eggs#1188] opened 2021-06-17 10:00 UTC
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version:  1.4.2
Daemon Version:  1.4.3
Service: Fivem
Modified: no
Expected Behavior:  Be able to install a fivem [server](url)
Actual Behavior:
at the end of the installation during the first launch I have this

https://www.casimages.com/i/210617121448368333.png.html

Steps to Reproduce: (Step by step what to do to cause the issue)

**Comment by Software-Noob** [comment] 2021-06-17 12:03
Duplicate of #1187

**Closed** 2021-06-17 12:04 UTC
