### ISSUE TITLE
FiveM not working

### ISSUE THREAD

**Issue by scooperdive** [parkervcp/eggs#1224] opened 2021-07-04 21:55 UTC
### Panel Version

1.4.2

### Wings Version

1.4.4

### Service

gta/fivem

### Modified

No, I did not modify the egg

### Expected Behavior

Press start and the server boots

### Actual Behavior

the server keeps spamming "This environment is not supported for running the Cfx.re platform server. Please run the Cfx.re platform server on a machine you control directly (i.e. not using a GSP panel)." in console

### Steps To Reproduce

step 1: install egg
step 2: install server using egg
step 3: press start

**Comment by FoksVHox** [comment] 2021-07-04 21:57
Duplicate of #1187

**Closed** 2021-07-04 21:58 UTC
