### ISSUE TITLE
[Bug]: ET Legacy

### ISSUE THREAD

**Issue by Placeb0h** [parkervcp/eggs#1646] opened 2022-05-11 11:08 UTC
### Panel Version

1.7.0

### Wings Version

1.6.0

### Service

ET Legacy

### Modified

No, I did not modify the egg

### Expected Behavior

Server to install and start correctly

### Actual Behavior

When going through the installation steps and unpacking the original Wolf: ET files it doesn't unpack them. On the console this error happens:

```
Cannot write to 'enemy_territory.zip' (Success).
Unpacking enemy territory files
Archive:  enemy_territory.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

Which then causes the following issue as it doesn't have the original files in place:

```
FS_InitFilesystem: Original game data files not found.

Please copy pak0.pk3 from the 'etmain' path of your Wolfenstein: Enemy Territory installation to:

"./etmain"
```

To manually fix I just upload the pak0.pk3 to the etmain folder but would like it to be done automatically.

### Steps To Reproduce

Step 1 Add egg to Pterodactyl Panel
Step 2 Create New Server
Step 3 Failed to install with above errors.

### Install logs

For some reason this command wasn't working

**Comment by parkervcp** [comment] 2022-05-11 11:27
Can you get the install logs for this failure?

**Comment by Placeb0h** [comment] 2022-05-11 11:40
For some reason that command wasn't doing anything but I have got the latest install log and uploaded to PasteBin for you :)

https://pastebin.com/JMEwug2A

**Comment by Placeb0h** [comment] 2022-05-11 17:18
Sorry to double post, any updates on this?

**Comment by parkervcp** [comment] 2022-05-11 19:26
The install worked for me and I see no issues here.

**Comment by Placeb0h** [comment] 2022-05-11 21:47
I'm not sure what the issue could be but it doesn't seem to do it automatically for me. I'm on Ubuntu 20.04, not sure if that has any effect

**Comment by Placeb0h** [comment] 2022-05-11 22:48
It seems to download 16% (42.61M) and then just stops, like I've run out of memory or something. I can assure you I haven't run out of memory.

**Comment by parkervcp** [comment] 2022-05-11 22:50
Can you run `df -h` on that?

**Comment by Placeb0h** [comment] 2022-05-11 23:05
Yeah that command works. It brings up this:

`Filesystem             Size  Used Avail Use% Mounted on
tmpfs                  390M  1.5M  388M   1% /run
/dev/mapper/vg00-lv01  118G  8.7G  104G   8% /
tmpfs                  1.9G     0  1.9G   0% /dev/shm
tmpfs                  5.0M     0  5.0M   0% /run/lock
/dev/sda1              488M  243M  210M  54% /boot
tmpfs                  390M  4.0K  390M   1% /run/user/0
`

**Comment by parkervcp** [comment] 2022-05-12 01:36
That looks fine there. I am not sure what the issue is.

**Comment by Placeb0h** [comment] 2022-05-12 10:46
I can't figure it out either. I've done a lot of googling and everything just fails

**Comment by Placeb0h** [comment] 2022-05-13 11:37
So I just did a brief change of the script and changed it to just `wget https://cdn.splashdamage.com/downloads/games/wet/et260b.x86_full.zip` and it did the same thing and failed. So I went in terminal and ran that command in the /root/ folder and it downloaded it find. Not a clue whats happening

**Comment by parkervcp** [comment] 2022-05-13 18:24
It's a dns issue inside the container. This happens sometimes if the hosting service intercepts some dns queries.

You can change what dns addresses the container should use in the wings config.

**Comment by Placeb0h** [comment] 2022-05-13 19:22
Alright cool, thank you, I'll have a look into that and report back to you :)

**Comment by Software-Noob** [comment] 2022-07-02 15:54
Closing as this doesn't appear to be an issue with the egg itself nor has received any new responses.

**Closed by Software-Noob** 2022-07-02 15:54 UTC
Labels: Bug
