### ISSUE TITLE
Yatopia Egg Request

### ISSUE THREAD

**Issue by reputationpen** [parkervcp/eggs#1119] opened 2021-04-25 17:01 UTC
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Minecraft Yatopia Server)

Does this expand an already existing service: Y

Link to game: (https://yatopiamc.org/)

Links for server downloads: https://yatopiamc.org/download.html

Links for install steps/docs: It's the same as a normal minecraft server, but the jarfile is the yatopia one

**Comment by Software-Noob** [comment] 2021-04-25 17:03
Duplicate of #967 which was refused

**Comment by EsserGaming** [comment] 2021-06-25 20:10
The project is now archived

**Closed** 2021-07-07 22:30 UTC
Labels: egg request, new egg
