### ISSUE TITLE
[Bug]: ArmA 3 in Egg can't figure out how much resources it should use

### ISSUE THREAD

**Issue by ShieldNavalny** [parkervcp/eggs#2371] opened 2023-07-15 20:53 UTC
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

arma3

### Modified

No, I did not modify the egg

### Expected Behavior

- Install the server
- Install all the mods you need for you server
- Enable Verify Signature to 2
- Enter your server
- Play

### Actual Behavior

- Install the server
- Install all the mods you need for you server
- Enable Verify Signature to 2
- Stuck on a loading screen

### Steps To Reproduce

1. Import latest version of the egg 
2. Install the server inside your node
3. Insert a modlist.html to the root folder inside container
4. Change verifySignatures from 0 to 2 inside server.cfg
5. Start the server and try to enter

### Install logs

[REDACTED] (by @lilkingjr1 -- Steam credentials plain text)

**Comment by lilkingjr1** [comment] 2023-07-15 20:56
@ShieldNavalny Urgent: Your install logs leak your Steam account credentials. I recommend changing your password now.

**Comment by lilkingjr1** [comment] 2023-07-15 20:59
I have followed your steps to reproduce and cannot replicate the issue, meaning the issue is local to you. Stuck on a loading screen is usually an issue with your mission file, configuration files, mods, or keys (considering you're using `verifySignatures  = 2;`).

Also, how does your issue relate to the title?

**Comment by ShieldNavalny** [comment] 2023-07-15 21:09
You are very quick to respond :)
About the account, thanks for the message. I changed the password but it's more of a technical account for the server only.


So this bug is most likely due to the fact that ArmA 3 for some reason can't figure out what it can use inside the container for processing. There are multiple reports on ArmA 3 Discord server about this behaviour inside Docker container. 

[Judging by this forum post, the solution is to add the -cpucount startup parameter.
](https://forums.bohemia.net/forums/topic/242602-a3-ds-linux-verify-signature-failure-fix/)

And that does help with the problem. After adding this startup parameter everything working as excepted.
My guess is that globally due to arma not being able to detect what it can use on the game server very low server FPS and therefore processing anything is very slow. That's a theory though and I haven't tested this with #monitor.

**Comment by lilkingjr1** [comment] 2023-07-15 21:22
Yeh, it's a hard case to crack, as it seems even on bare metal Linux Arma tends to run a little slower than it's Windows binary, but only at scale (ie. 40+ players). This is on top of it potentially having a hard time determining CPU specs (depending on the root CPU) when running within a Docker container. Unfortunately, there's not much we can do from the Egg or Yolk side to remedy this issue regarding automatic detection, and it's more on Bohemia to fix (which they wont). Therefore, I'm going to close this issue as "can't repro. / won't fix" for the time being. However, I'm very interested in continuing the conversation and testing around using the `-cpucount` startup parameter, because, from my experience, `-cpucount` always caused a deterministic crash for me and I just wrote it off as a weird Docker container issue. I'm glad to hear it works for you, and I'll have to give it a try myself sometime soon. If it works, we could experiment with adding it to the Egg, or at least mentioning it in the README for advanced users.

**Closed by lilkingjr1** 2023-07-15 21:22 UTC
Labels: bug, not confirmed
