### ISSUE TITLE
Request: AzuraCast

### ISSUE THREAD

**Issue by Jelcoo** [parkervcp/eggs#1145] opened 2021-05-13 11:56 UTC
Service: AzuraCast

Does this expand an already existing service: N

Link to game: https://www.azuracast.com/

Links for server downloads: https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh

Links for install steps/docs: https://docs.azuracast.com/en/getting-started/installation/docker

**Comment by gOOvER** [comment] 2021-05-13 12:01
Ptero is not designed to host this. Docker install means not that it's compatible with Ptero.

**Comment by parkervcp** [comment] 2021-05-13 12:16
Duplicate of #953

**Closed by parkervcp** 2021-05-13 12:16 UTC
