### ISSUE TITLE
[Bug]: DayZ (Experimental)

### ISSUE THREAD

**Issue by jean-baptiste-d** [parkervcp/eggs#2239] opened 2023-04-26 21:18 UTC
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

dayz

### Modified

No, I did not modify the egg

### Expected Behavior

Connect me to the server.

### Actual Behavior

Error in the console :
```
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:0406506C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len
Error decrypting message: error:0406506C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
```

And it's impossible to connect to the server.

### Steps To Reproduce

1. Install server
2. Connect to the server

### Install logs

nop

**Comment by lilkingjr1** [comment] 2023-04-26 21:39
What version of the client are you using to connect?

**Comment by Skippygamer** [comment] 2023-05-06 19:35
I am haveing same problem with latest client version and latest server

**Comment by lilkingjr1** [comment] 2023-05-06 20:31
> I am haveing same problem with latest client version and latest server

Are you running the Experimental version of the client to connect?

**Comment by Skippygamer** [comment] 2023-05-06 20:53
No I'm using the standard  version

**Comment by QuintenQVD0** [comment] 2023-05-06 22:16
> No I'm using the standard version

Read the readme! You need the experimental client for this to work.

**Comment by QuintenQVD0** [comment] 2023-05-07 10:42
I am closing this as you did not read the readme. you have to have the experimental client for this to work

**Closed by QuintenQVD0** 2023-05-07 10:42 UTC
Labels: bug, not confirmed

**Comment by Dayron1195** [comment] 2023-06-14 02:23
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
22:22:54 Average server FPS: 15.89 (measured interval: 10 s)
22:22:54 Average server FPS: 15.89 (measured interval: 10 s)
22:22:54 Used memory: 1847755 KB
22:22:54 Used memory: 1847755 KB
22:22:54 Players: 8 in total
22:22:54 Players: 8 in total
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
Error decrypting message: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error

**Comment by lilkingjr1** [comment] 2023-06-14 03:32
@Dayron1195 Are you having any functional issues? Or are you just getting errors? I think these are safe to ignore as long as you don't have functional issues. It's also not an issue caused by the egg.

**Comment by jcads** [comment] 2023-10-11 13:20
@Dayron1195 were you able to connect to your server?

**Comment by HerrSammyDE** [comment] 2023-10-30 20:02
I use the Experimental Client and the server could be started without any problems. I get the same error.
