### ISSUE TITLE
[Bug]: ark survival ascended 

### ISSUE THREAD

**Issue by Cobras-Hosting** [parkervcp/eggs#2536] opened 2023-11-01 23:39 UTC
### Panel Version

1.11.5

### Wings Version

1.11.7

### Service

rcon connection 

### Modified

No, I did not modify the egg

### Expected Behavior

i installed the egg i then created a server to run a few test to see if i can log on to the server and be able to play the game that what i would like to see that would happen i have never had this before 

### Actual Behavior

waiting for rcon connection...
cli: auth: rcon: rcon: read packet size: read tcp 127.0.0.1:41434->127.0.0.1:37015: i/o timeout
waiting for rcon connection...
cli: auth: rcon: rcon: read packet size: read tcp 127.0.0.1:55220->127.0.0.1:37015: i/o timeout
waiting for rcon connection...
[2023.11.01-23.23.09:075][  0]Server: "A Pterodactyl Hosted Server" has successfully started!
[2023.11.01-23.23.09:441][  0]Commandline:  "TheIsland_WP?listen?MaxPlayers=30?SessionName=A Pterodactyl Hosted Server?Port=2004?QueryPort=27015?RCONPort=37015?RCONEnabled=True?ServerPVE=True?ServerPassword=?ServerAdminPassword=password" -WinLiveMaxPlayers=30 -oldconsole -servergamelog
[2023.11.01-23.23.09:441][  0]Full Startup: 38.23 seconds
[2023.11.01-23.23.09:441][  0]Number of cores 12
Waiting commands for 127.0.0.1:37015 (or type :q to exit)
container@pterodactyl~ Server marked as running...
> [2023.11.01-23.23.13:245][  2]wp.Runtime.HLOD = "1"

i would just like some help i have worked on anything like this in a long time as everytime i try and log on to the server via the game it just keeps saying connection time out

### Steps To Reproduce

step 1 installed the server 
step 2 click start to start the server 

if i havnt filled this in right please let me know 

### Install logs

https://pteropaste.com/iyz8yynndac0

**Comment by parkervcp** [comment] 2023-11-01 23:40
I am going to go on a say this is not an rcon issue but something else

**Comment by Cobras-Hosting** [comment] 2023-11-01 23:42
right is there anything i can do to be able to get on the server or will i have to wait for an egg update or just the server to update

**Comment by parkervcp** [comment] 2023-11-02 00:05
You are currently the only one having this issue so far as I know. Until it can be re-created this will have to wait.

**Comment by Cobras-Hosting** [comment] 2023-11-02 00:11
right ok thank you

**Comment by dagbs** [comment] 2023-11-02 00:23
If the server is marked as running and the CPU is greater than ~5% and RAM around 10GB+ then there is nothing wrong with the server. The only known issue with a running server is that you can't have more than one running on an IP at a time.

**Comment by Cobras-Hosting** [comment] 2023-11-02 00:24
that is the only ark server on there and it just wont connect to the server

**Comment by dagbs** [comment] 2023-11-02 00:27
Then the issue is on forwarding of the ports.

**Comment by Cobras-Hosting** [comment] 2023-11-02 00:28
i have tryed that and there still nothing i just keep gettion connection time out

**Comment by MaroSandor** [comment] 2023-11-02 16:38
We have a little problem with the server. The server has two players playing via NVIDIA GeForce Now and the tribe log file is incredibly large compared to other logs! While an average tribe log is 8-10 KB, theirs is 190-210 KB. What could be the problem? What solution do you recommend?

**Comment by gOOvER** [comment] 2023-11-02 16:50
> We have a little problem with the server. The server has two players playing via NVIDIA GeForce Now and the tribe log file is incredibly large compared to other logs! While an average tribe log is 8-10 KB, theirs is 190-210 KB. What could be the problem? What solution do you recommend?

thats not an egg problem. Ask the ARK devss

**Comment by gOOvER** [comment] 2023-11-02 17:02
> Then the issue is on forwarding of the ports. Please reach out in discord for help as this is not an egg issue.

No, i get also timeouts without haveing ufw or a router in fron t of it

**Comment by vp-en** [comment] 2023-11-03 10:00
> that is the only ark server on there and it just wont connect to the server 

Try setting your server name to something with no spaces in it. E.g. "MyTestServer" or something.

**Comment by MachinegunMarty** [comment] 2023-11-04 23:19
Sorry but the latest egg still doesn't work for me...

1st: It's sets the port to 27015 instead of 7777 
So it sets port and querryport to 27015. Test: Roll out a fresh egg and look at the startup tab.

2nd: I can't connect to the server: Time-out

I can find it in the unofficial listing in game. I tried with and without a password and both times i could see it in the listing.
I can see in pterodactyl that it's using 5-7% CPU and 10,5 GiB MEM.
I get server is running and after that wp.runtime.HLOD = 1. Every 15 mins it's saving world. Can't connect tho.
No FW on Arch Linux server, no FW on WINpc. NAT: 7777, 7778, 27015 tcp + udp open to server. 
Works for all my Ark Survival Evolved and Minecraft servers.

**Comment by Knaox** [comment] 2023-11-04 23:28
> Sorry but the latest egg still doesn't work for me...
> 
> 1st: It's sets the port to 27015 instead of 7777 So it sets port and querryport to 27015. Test: Roll out a fresh egg and look at the startup tab.
> 
> 2nd: I can't connect to the server: Time-out
> 
> I can find it in the unofficial listing in game. I tried with and without a password and both times i could see it in the listing. I can see in pterodactyl that it's using 5-7% CPU and 10,5 GiB MEM. I get server is running and after that wp.runtime.HLOD = 1. Every 15 mins it's saving world. Can't connect tho. No FW on Arch Linux server, no FW on WINpc. NAT: 7777, 7778, 27015 tcp + udp open to server. Works for all my Ark Survival Evolved and Minecraft servers.

egg currently has some problems with port forwarding. 
In particular, if you change the default port, the server will timeout. this is a known problem.

I hope it will be solved, because you can't create several servers, which is very inconvenient when you want to create different servers for your friends, for example...

I'm counting on you, thanks for what you're already doing.

**Comment by MachinegunMarty** [comment] 2023-11-05 00:30
Out of conversation on discord:

I had my primary network port set to 27015, that's why the port was set to 27015.
You have to set your primary network port to 7777, then it uses port 7777.

This means that if you would want to run more servers you just set your 2nd server to 7779(+1), 3rd server 7781(+1) etc.

But you can only host 1 server from 1 ip, but technically...

**Comment by MachinegunMarty** [comment] 2023-11-05 20:42
I feel like an idiot... It's was my Hairpin NAT rule causing trouble. For me to be able to acces the external adresses of my servers from the same LAN, i have to add a masquerade rule.
That masquerade rule was set to tcp only. Removed tcp only and worked right away.
Has been working for years so didn't look into that. Guess all my servers just needed tcp to work up until now.

So in short:

In your Ark Ascended server, running In the panel add:
<serverip>:7777  (Primary)
<serverip>:7778
<serverip>:27015
<serverip>:37015

In your Router/ Firewall open/ Port Forward/ NAT:
<serverip>:7777 (TCP + UDP)
<serverip>:7778 (TCP + UDP)
<serverip>:27015 (TCP + UDP)

The server name has spaces, - and ] in it and a server password set, and no connection timeouts anymore.

So apologies, the egg is working great. 
For me it was a rule blocking my UDP traffic.

**Closed** 2023-11-06 13:58 UTC
Labels: bug, not confirmed

**Comment by Cobras-Hosting** [comment] 2023-11-06 16:09
> I feel like an idiot... It's was my Hairpin NAT rule causing trouble. For me to be able to acces the external adresses of my servers from the same LAN, i have to add a masquerade rule. That masquerade rule was set to tcp only. Removed tcp only and worked right away. Has been working for years so didn't look into that. Guess all my servers just needed tcp to work up until now.
> 
> So in short:
> 
> In your Ark Ascended server, running In the panel add: :7777 (Primary) :7778 :27015 :37015
> 
> In your Router/ Firewall open/ Port Forward/ NAT: :7777 (TCP + UDP) :7778 (TCP + UDP) :27015 (TCP + UDP)
> 
> The server name has spaces, - and ] in it and a server password set, and no connection timeouts anymore.
> 
> So apologies, the egg is working great. For me it was a rule blocking my UDP traffic.

i just seen your message and i am new to this can you able to show me how to sort this please
