### ISSUE TITLE
OpenRct2 Egg Request

### ISSUE THREAD

**Issue by Drprofmayer2** [parkervcp/eggs#543] opened 2020-05-29 04:31 UTC
Service:RollerCoaster Tycoon 2

Does this expand an already existing service: N

Link to game: https://openrct2.org/

Links for server downloads: https://openrct2.org/downloads

Links for install steps/docs: https://openrct2.org/quickstart

Just thought this would be a cool egg to have I enjoy playing this with friends.

**Comment by parkervcp** [comment] 2020-08-03 17:09
Duplicate of #381

**Closed by parkervcp** 2020-08-03 17:09 UTC
