### ISSUE TITLE
[Bug]: Arma 3 egg with more than one HC won't start

### ISSUE THREAD

**Issue by Stephan-Fis** [parkervcp/eggs#1412] opened 2021-11-24 14:54 UTC
### Panel Version

1.6.6

### Wings Version

1.5.3

### Service

Arma3

### Modified

No, I did not modify the egg

### Expected Behavior

Server should start with more then one headless-Client

### Actual Behavior

Server won't start and shows output:
 Waiting for './serverprofile/DataCache/cache_lock' to be available

When i delete the file, the server won't start.

I have several mods installed.
It is irelevant, if these are loaded or installed.
When i configure only one HC server starts. Wiht two ore more nothing happens.

### Steps To Reproduce

1. latest version
2. install server
3. configure more then one hc
4. start server

### Relevant log output

```shell
[UPDATE]: Game server is up to date!

[UPDATE]: Checking all Steam Workshop mods for updates...
[UPDATE]: Steam Workshop mod update check complete!

[STARTUP]: Clearing Headless Client profiles cache...

[STARTUP]: Starting 2 Headless Client(s).
[STARTUP]: Headless Client 1 launched.
[STARTUP]: Headless Client 2 launched.

[STARTUP]: Starting server with the following startup command:
./arma3server_x64 -ip=0.0.0.0 -port=2302 -profiles=./serverprofile -bepath=./battleye -cfg=basic.cfg -config=server.cfg -mod="@1180533757;@1180534892;@1224892496;@1638341685;@1673456286;@333310405;@450814997;@463939057;@583496184;@583544987;@767380317;@773125288;@773131200;@843425103;@843577117;@843593391;@861133494;@884966711;@945476727;" -serverMod="" -noLogs

14:51:22 SteamAPI initialization failed. Steam features won't be accessible!
14:51:22 Waiting for './serverprofile/DataCache/cache_lock' to be available
14:51:23 Waiting for './serverprofile/DataCache/cache_lock' to be available
14:51:24 Waiting for './serverprofile/DataCache/cache_lock' to be available
14:51:25 Waiting for './serverprofile/DataCache/cache_lock' to be available
```

**Comment by Stephan-Fis** [comment] 2021-11-24 15:23
sorry,

tested again.
Unfortunatelly no HC can be started.
I deleted the file and tried again.
Is it possible to change the cache-folder for each HC and the main server?

**Comment by lilkingjr1** [comment] 2021-11-25 01:53
The `Waiting for './serverprofile/DataCache/cache_lock' to be available` message is normal when running HCs, because both the main server and each HC are running in the same container and using the same files to boot (I think it may even happen with just one HC, but I know it definitely happens with two because I run two myself). When Arma boots, I believe it locks `cache_lock` (and probably other files) while it boots to prevent possible interference during boot, and then unlocks it once it's fully booted. Therefore, any other server or client (like the HCs) trying to boot at the same exact time have to wait for it to become available again before they can start their boot process. This "issue" gets compounded for each HC you run, and can lengthen the wait time based on number of mods to load. The way the Yolks image boots Arma is it actually boots the HCs first, and then finally the main server. Therefore, because the main server is the only one that prints to console (unless you have "[ADVANCED] HC HIDE CONSOLE OUTPUT" set to `0`), it will spam this message until it is freed up to be used to boot. Deleting the file may brick your server since it is a required file, and verifying your server install may not fix it (depending how smart SteamCMD is).

So, here's what I recommend trying:
1. Create a brand new Arma server on the panel with no mods.
2. Configure it to use **two** HCs (which is more than one for testing, but not overkill either like 3 or more is).
2b. [Optional] Set "[ADVANCED] HC HIDE CONSOLE OUTPUT" to `0` to have verbose logging if you'd like. You see even more spam of the DataCache message. At first you'll see it being printed 2 at a time, but over time you'll see it only print once, and then 0 as the main server kicks in to boot.
3. Start the server **and be patient**. A server, 2 HCs, and 55 mods takes about 5+ real minutes to boot for me (iirc).

**Comment by lilkingjr1** [comment] 2021-12-31 02:36
@Stephan-Fis Is this abandoned?

**Comment by lozanoeg** [comment] 2022-01-11 20:43
@lilkingjr1 i've been having a similar issue but for me i just get core dumps with any headclients set

**Comment by lilkingjr1** [comment] 2022-01-11 21:00
> @lilkingjr1 i've been having a similar issue but for me i just get core dumps with any headclients set

@lozanoeg Are you having this issue on a freshly installed server, using the latest egg version, with no mods and no modifications to config files? If so, can you post your startup logs? If the startup logs seem irrelevant or don't seem to show anything interesting, you can remove `-noLogs` from your Extra Startup Parameters variable for verbose logging.

**Comment by lozanoeg** [comment] 2022-01-11 22:04
it has mods now but yes it was a fresh install and was still getting this error and the newest egg

**Comment by lilkingjr1** [comment] 2022-01-11 22:15
@lozanoeg Are you running the server on a 64-bit system? If so, you need to change your Server Binary startup variable to `arma3server_x64`. Your issue stems from trying to load the 32-bit version of Arma, which makes the startup script try to load 32-bit libraries to support it. Which, to be honest, I'm not even sure if those libraries are still supported by the latest version of Arma; I haven't tested it in a while.

**Comment by lozanoeg** [comment] 2022-01-11 22:30
it is unrelated it just had the same cause, the one problem with this is that the server binary on x64 is pretty unstable and causes a lot of issues with loading missions so i was running it in x32. if i find a workaround for that binary issue i'll make a merge request due to this issue

**Comment by lilkingjr1** [comment] 2022-01-11 23:52
> it is unrelated **it just had the same cause**

Not really, unless I'm mistaken. In theory, your server shouldn't start, regardless of how many HCs you have (like 0 or 1). If this is true, I would recommend making a separate issue (for organizational purposes) titled something like "Arma 3 32-bit binary won't start", so the separate issue can get the attention it deserves.

> the server binary on x64 is pretty unstable and causes a lot of issues with loading missions so i was running it in x32

It shouldn't? The architecture should have no bearing on how Arma loads missions internally. However, the 64-bit build *could* be argued to be less stable in general, but this issue should be raised with the app's developers. I'd argue myself that *all* Linux binaries are less stable Arma's Windows binaries just from experience and testing, but I don't have much concrete proof for this. But nonetheless, if you have some evidence from your issues of loading missions on x64 (like logs, etc), I'd be interested to see them.

> if i find a workaround for that binary issue

It's less of a binary issue and more of a library issue with `libnss-wrapper`. I've just now taken the time to look at the [long commit history of the Arma 3 image](https://github.com/parkervcp/images/commits/game/arma3?after=59363ecb51eaac643c34dae58c9f7c915720f5e2+104&branch=game%2Farma3). It's a pretty dirty history, with some people (sadly, including myself), just "throwing images at the wall to see what sticks". It seems to start with a regression created in parkervcp/images#22, where the `libnss-wrapper` package was added to the image for user creation/management, needlessly creating a dependency. When I rewrote the image, I didn't know what it was and just assumed it was a prerequisite of Arma because it was explicitly loaded in the old `entrypoint.sh`, so I kept it. However, after some research, it looks like it's not needed at all and can be removed, along with a bunch of other junk packages in the image. Please make a new issue like I mentioned above, and I'll see if I can craft a PR that cleans up the image when I have time, which will also resolve your issue. Or, you're welcome to submit a PR yourself with the fix if you would rather not wait. Thank you nonetheless for bringing this issue to light.

**Comment by lozanoeg** [comment] 2022-01-12 00:52
It was noticed because when I was running the 32 bit binary it would launch fine every time with no head clients, 75% of the time with 1 head client and any higher would not start but you are right it seems to be an issue with the 32 bit binary, when I'm back to my computer I'll create another issue and then I'll also drop in some of the logs with 32 bit the mission loading correctly vs not with the 64 bit just for completeness

**Comment by lilkingjr1** [comment] 2022-01-12 01:59
> It was noticed because when I was running the 32 bit binary it would launch fine every time with no head clients

Really?... I'm surprised...

> I'll create another issue and then I'll also drop in some of the logs with 32 bit the mission loading correctly vs not with the 64 bit just for completeness

Awesome, thank you very much!

**Comment by lilkingjr1** [comment] 2022-01-12 08:36
@Stephan-Fis Awesome! Yeh, that many mods with two HCs will take some time to load for sure.

If you feel your issue was resolved, feel free to close this issue. Thanks.

**Closed** 2022-01-12 09:27 UTC
Labels: Bug
