### ISSUE TITLE
Azuracast

### ISSUE THREAD

**Issue by CEO-Enzo** [parkervcp/eggs#1583] opened 2022-03-14 00:06 UTC
### Does this expand an already existing service

No

### Link to a game or software

https://www.azuracast.com/

### Links for the download

https://github.com/AzuraCast/AzuraCast

### Links for the install docs

https://docs.azuracast.com/en/getting-started/installation/docker

**Comment by Software-Noob** [comment] 2022-03-14 00:08
Duplicate of #953 and #1581

**Closed by Software-Noob** 2022-03-14 00:08 UTC
Labels: Egg Request
