### ISSUE TITLE
Farming Simulator

### ISSUE THREAD

**Issue by rowansc1** [parkervcp/eggs#1160] opened 2021-05-29 22:39 UTC
Service: (Ex. minecraft/factorio/etc)
Farming Simulator 19 Server

Does this expand an already existing service: Y/N
SteamCMD

Link to game: (Ex. minecraft.net/factorio.com/etc)
https://www.farming-simulator.com/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.
https://www.farming-simulator.com/

Links for install steps/docs:
Normally launching the game. Can't find too much on it on google.

**Comment by parkervcp** [comment] 2021-05-29 23:35
duplicate of #307

**Closed by parkervcp** 2021-05-29 23:35 UTC
