### ISSUE TITLE
[Egg Request]: <Software> Wordpress

### ISSUE THREAD

**Issue by CrystalVortex** [parkervcp/eggs#2088] opened 2023-01-25 09:22 UTC
### Does this expand an already existing service

Yes

### Link to a game or software

https://wordpress.org/download/

### Links for the download

https://wordpress.org/download/

### Links for the install docs

https://wordpress.org/documentation/article/how-to-install-wordpress/

**Comment by Boy132** [comment] 2023-01-25 09:24
Duplicate of https://github.com/parkervcp/eggs/issues/1293#issuecomment-897142125

**Closed by Boy132** 2023-01-25 09:24 UTC
Labels: egg request
